#!/bin/bash
export PATH="$PATH:$OPENSHIFT_DATA_DIR/bin:$OPENSHIFT_DATA_DIR/sbin"
export PYTHONPATH="$OPENSHIFT_REPO_DIR"

nginx                       >> "$OPENSHIFT_DIY_LOG_DIR/nginx.stdout.log"   2>&1 &
python3 -m yoboard.database >> "$OPENSHIFT_DIY_LOG_DIR/database.stdout.log" 2>&1 &
gunicorn --config "$OPENSHIFT_REPO_DIR/configs/gunicorn.py" yoboard.viewserver:app >/dev/null 2>&1
