#!/bin/bash
killps() {
  kill `ps -ef | grep $1 | grep -v grep | awk '{ print $2 }'`
}

if [ -f "$OPENSHIFT_TMP_DIR/gunicorn.pid" ]
then
  killps 'yoboard.database'                   >/dev/null 2>&1
  killps 'nginx'                              >/dev/null 2>&1
  kill $(cat $OPENSHIFT_TMP_DIR/gunicorn.pid) >/dev/null 2>&1
fi
