#!/bin/bash
function killps {
  # Kill a process given a part of its name.
  #
  # Pretty much equivalent to pkill?
  #
  kill $1 `ps -ef | grep $2 | grep -v grep | awk '{ print $2 }'`
}

killps -TERM 'yoboard.database'
killps -TERM 'nginx'
killps -INT  'gunicorn'
# There can be no errors.
true
